global:
  scrape_interval: 15s
  evaluation_interval: 15s
  rule_files: 
    - recording_rules.yml
    
scrape_configs:
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  
  - job_name: 'jenkins'  
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['${JENKINS_HOST}:8080']
