global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo:27017']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8081']
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:4000']
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']