pipeline {
    agent any

    environment {
        IMAGE_NAME = 'blog_nextjs_app'
        CONTAINER_NAME = 'blog_nextjs_container'
        PORT = '3000'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/jjoevv/blog_nextjs.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    if (isUnix()) {
                        sh "docker build -t $IMAGE_NAME ."
                    } else {
                        bat "docker build -t %IMAGE_NAME% ."
                    }
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    if (isUnix()) {
                        sh "docker rm -f $CONTAINER_NAME || true"
                        sh "docker run -d --name $CONTAINER_NAME -p $PORT:$PORT $IMAGE_NAME"
                    } else {
                        bat "docker rm -f %CONTAINER_NAME% || exit 0"
                        bat "docker run -d --name %CONTAINER_NAME% -p %PORT%:%PORT% %IMAGE_NAME%"
                    }
                }
            }
        }
    }

    post {
        success {
            echo "✅ App is running at http://localhost:$PORT"
        }
        failure {
            echo '❌ Build failed!'
        }
    }
}
