pipeline {
  agent {
    docker {
      image 'node:18'
      args '-u node --workdir /home/node'
    }
  }

  environment {
    APP_DIR = 'reactapp'
    HOME = '/var/lib/jenkins'
    NPM_CONFIG_CACHE = "${HOME}/.npm"
  }

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/jjoevv/blog_nextjs.git'
      }
    }
    stage('Test Shell') {
        steps {
            sh 'echo Hello from Shell'
        }
    }


    stage('Install Dependencies') {
      steps {
        dir("${APP_DIR}") {
          sh '''
            echo " Cleaning old dependencies..."
            rm -rf node_modules package-lock.json
            npm cache clean --force

            echo " Installing packages..."
            npm install
          '''
        }
      }
    }
  }

  post {
    success {
      echo "✅ App is running"
    }
    failure {
      echo "❌ Build failed"
    }
  }
}
// This Jenkinsfile is designed to run a React application using a Node.js Docker image.
// It checks out the code from a Git repository, installs dependencies, and cleans up old files